### ISSUE TITLE
Responsive breakpoints max-* is not working

### ISSUE THREAD

**Issue by longprao** [songkeys/tailwind-preset-mantine#10]
I have setup a barebone app based on your template, and I notice that by adding preset mantine, it breaks the "max" breakpoints, so that means these are no longer working: `max-sm:`, `max-md:`, `max-lg:`, `max-xl:`.

For example: `max-lg:flex`.

It is helpful for desktop-first designs.

Just removing these from the tailwind config will make it work again:

```  
  presets: [
    tailwindPresetMantine({
      mantineBreakpoints: breakpoints,
      mantineColors: colors,
    }),
  ],
```

Do you have a solution for this?

**Comment by songkeys** [comment]
This looks like a tailwind problem to me. When using non-px value (like [em in mantine](https://github.com/mantinedev/mantine/blob/1d62b4e78fc20ba780e4e556d87199e3b92a3608/packages/%40mantine/core/src/core/MantineProvider/default-theme.ts#L77-L83)), the `max-*` won't work. Example: https://play.tailwindcss.com/Hxxr9zRmpm

Here is a wordaround: https://github.com/tailwindlabs/tailwindcss/issues/13022#issuecomment-2006752527 . I can add this to the next version. Let me know if you have a better idea.

**Comment by songkeys** [comment]
This has been resolved in https://github.com/songkeys/tailwind-preset-mantine/releases/tag/v1.3.2
