### ISSUE TITLE
Clarification needed on custom theme usage with MantineProvider

### ISSUE THREAD

**Issue by artemchs** [songkeys/tailwind-preset-mantine#6]
## Reproduction
I've created a minimal repository that demonstrates this issue: [next-app-mantine-tailwind-template-issue](https://github.com/artemchs/next-app-mantine-tailwind-template-issue)

Steps to reproduce:
1. Clone the repository
2. Install dependencies (`pnpm install`)
3. Check the TypeScript error in `src/app/layout.tsx` on line 50

## Description
There seems to be a disconnect between the documentation for custom theme usage and how it should be implemented with `MantineProvider`. The current documentation shows how to configure the Tailwind preset with a custom Mantine theme, but it's not clear how this should work with `MantineProvider`.

## Current Behavior
Following the documentation, I created a theme configuration like this:

```typescript
// theme.ts
import tailwindPresetMantine from "tailwind-preset-mantine";
import { createTheme } from "@mantine/core";

const mantineTheme = createTheme({
  // custom theme options
});

const themeConfig = {
  presets: [
    tailwindPresetMantine({
      mantineColors: mantineTheme.colors,
      mantineBreakpoints: mantineTheme.breakpoints,
    }),
  ],
};

export default themeConfig;
```

However, when trying to use this configuration with `MantineProvider`:

```typescript
<MantineProvider theme={themeConfig}>{children}</MantineProvider>
```

I get the following TypeScript error:
```
Type '{ presets: Config[]; }' has no properties in common with type 'PartialObjectDeep<MantineTheme, {}>'.ts(2559)
```

## Expected Behavior
I expect to be able to use my custom theme with MantineProvider without any type issues.

## Environment
- `tailwind-preset-mantine` version: [^1.2.1]
- `@mantine/core` version: [^7.13.4]
- Next.js version: [^15.0.1]

**Comment by songkeys** [comment]
Hi there! It looks like there might be a little misunderstanding in how to use it.

I've made some updates to the template to include the custom theme code in this [commit](https://github.com/songkeys/next-app-mantine-tailwind-template/commit/b50ed8d3b8707988493ab4d0f481d5a379a109cf).

Please take a look, and let me know if you have any questions!

**Comment by artemchs** [comment]
Thank you for clarifications. Yes, not it works as expected with no type issues.

**Comment by songkeys** [comment]
I've also updated the docs to make it more clear for custom themes:

https://github.com/songkeys/tailwind-preset-mantine#custom-mantine-theme
